version: "3.1"
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - db
        ports: 
            - "3000:3000"
    db:
        build: 
            context: ./db
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment: 
            PGPORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: webapp
