version: "3.1"
services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - db
        ports: 
            - "3000:3000"
    db:
        image: postgres:12.1
        restart: always
        environment: 
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_USER=postgres"
